<a href="https://colab.research.google.com/github/nadivaagista07/Scientific-Computing/blob/main/SC_Sesi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SESI 1


In [ ]:
print ("Hello")

Hello


In [ ]:
import time

In [ ]:
print (time. ctime())

Thu Feb  6 04:43:56 2025


In [ ]:
z = "hello"
y = 20
c = 30.9
f = ["Apple", "Berry"]

z, y, c, f
print (z, y, c, f)

hello 20 30.9 ['Apple', 'Berry']


In [ ]:
o = int (1)
y = int (2.8)
z = int ("3")
j = str (20)

print (o, y, z, j)

1 2 3 20


In [ ]:
a = "Hello"
b = " Word"
c = a + b
print (c)

Hello Word


In [ ]:
a = "Hello Word"
print (a[1])

print (len(a))

e
10


In [ ]:
b = "Binus Univ"
print (b[2:5])

c = "Binus Univ"
print (c[:5])

d = "Binus Univ"
print (d[2:])


nus
Binus
nus Univ


In [ ]:
a = "Hello"
print (a.upper())

b = "Hello"
print (a.lower())

c = "Hello"
print (a.replace("H", "J"))

HELLO
hello
Jello


In [ ]:
nama = "sam"
x = 19
string = "nama saya {} umur {}"
print (string.format(nama,x))

nama saya sam umur 19


In [ ]:
nama = "Grace"
for i in enumerate (nama):
  print (i)

(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [ ]:
def perbandingan (a,b) :
  if a>b:
    print ("a lebih dari b")
  if a<b:
    print ("a kurang dari b")
  else :
    print ("a = b")

In [ ]:
perbandingan (4,8)

a kurang dari b


In [ ]:
i = 1
while i < 6 :
  print (i)
  i += 1

1
2
3
4
5


In [ ]:
i = 3
for i in range (0,6):
  print (i)

0
1
2
3
4
5


In [ ]:
for o in range(2, 41):
    if o % 2 == 0:
        print(o, "adalah bilangan genap")
    else:
        print(o, "adalah bilangan ganjil")

2 adalah bilangan genap
3 adalah bilangan ganjil
4 adalah bilangan genap
5 adalah bilangan ganjil
6 adalah bilangan genap
7 adalah bilangan ganjil
8 adalah bilangan genap
9 adalah bilangan ganjil
10 adalah bilangan genap
11 adalah bilangan ganjil
12 adalah bilangan genap
13 adalah bilangan ganjil
14 adalah bilangan genap
15 adalah bilangan ganjil
16 adalah bilangan genap
17 adalah bilangan ganjil
18 adalah bilangan genap
19 adalah bilangan ganjil
20 adalah bilangan genap
21 adalah bilangan ganjil
22 adalah bilangan genap
23 adalah bilangan ganjil
24 adalah bilangan genap
25 adalah bilangan ganjil
26 adalah bilangan genap
27 adalah bilangan ganjil
28 adalah bilangan genap
29 adalah bilangan ganjil
30 adalah bilangan genap
31 adalah bilangan ganjil
32 adalah bilangan genap
33 adalah bilangan ganjil
34 adalah bilangan genap
35 adalah bilangan ganjil
36 adalah bilangan genap
37 adalah bilangan ganjil
38 adalah bilangan genap
39 adalah bilangan ganjil
40 adalah bilangan genap


In [ ]:
import numpy as np

In [ ]:
x = np.array ([[1,2,3],[3,6,7]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
y = np.array ([[8,2,9],[3,5,7]])
y

array([[8, 2, 9],
       [3, 5, 7]])

In [ ]:
print (x+y)

[[ 9  4 12]
 [ 6 11 14]]


In [ ]:
data = np.array ([10,9,8,7,6])
print ("Rata rata:", np.mean(data))
print ("Maksimum:", np.max(data))
print ("Minimum:", np.min(data))
print ("Standar Devisiasi:", np.std(data))

Rata rata: 8.0
Maksimum: 10
Minimum: 6
Standar Devisiasi: 1.4142135623730951


In [3]:
def calculate(UAS, UTS, ASG):
    return (UAS * 0.5) + (UTS * 0.3) + (ASG * 0.2)

def grading(final_score):
    if 90 <= final_score <= 100:
        return "A"
    elif 85 <= final_score <= 89:
        return "A-"
    elif 80 <= final_score <= 84:
        return "B+"
    elif 75 <= final_score <= 79:
        return "B"
    elif 70 <= final_score <= 74:
        return "B-"
    elif 65 <= final_score <= 69:
        return "C"
    elif 60 <= final_score <= 64:
        return "D"
    elif 11 <= final_score <= 59:
        return "E"
    else:
        return "F"

while True:
    username = input("Masukkan username: ")
    password = input("Masukkan password: ")
    if password == "Admin123":
        print("Login berhasil!\n")
        break
    else:
        print("Password salah! Coba lagi.\n")

nama = input("Masukkan nama mahasiswa: ")

def input_nilai(prompt):
    while True:
        try:
            nilai = float(input(prompt))
            if 0 <= nilai <= 100:
                return nilai
            else:
                print("Nilai harus antara 0 - 100.")
        except ValueError:
            print("Harap masukkan angka yang valid.")

UAS = input_nilai("Masukkan nilai UAS: ")
UTS = input_nilai("Masukkan nilai UTS: ")
ASG = input_nilai("Masukkan nilai ASG: ")

final_score = calculate(UAS, UTS, ASG)
grade = grading(final_score)

print("\n============================================")
print(f"Hasil perolehan nilai {nama}")
print(f"Final Score: {final_score:.2f}")
print(f"Grade: {grade}")


Masukkan username: Nadiva07
Masukkan password: Admin123
Login berhasil!

Masukkan nama mahasiswa: Nadiva Agista
Masukkan nilai UAS: 90
Masukkan nilai UTS: 85
Masukkan nilai ASG: 100

Hasil perolehan nilai Nadiva Agista
Final Score: 90.50
Grade: A
